### PR TITLE
Ward API with disable and destroy

### PR DESCRIPTION
**Pull request by Wacky-Mole**
Added a basic Ward API and DisableWardPlayerIsIn function for a mod that I am working on. 
 Please make sure destroying a ward doesn't hurt WIL. 
Not a priority, so please add whenever you do your next patch. 
-WM

### CODE REVIEW

**Comment by Wacky-Mole** [comment]
Hey Azu,
How is your API coming along?
Are you able to add something like this PR DisableWardPlayerIsInAPI?
-WM

**Comment by AzumattDev** [comment]
I had forgotten about this entirely. I'll work on the API this weekend. Wrote it down.

**Comment by AzumattDev** [comment]
Going to rework the mod a little (at least the asset) and add more to the API for you.

**Comment by AzumattDev** [comment]
Closing this as I'll do the work on my end.

**Pull request closed without merging**
